name: BetterWarps
version: 0.0.1
main: Electro\BetterWarps\BetterWarps
api: 5.0.0
author: Electro

commands:
  warp:
    usage: /warp <create/remove>
    description: Create/Remove a Warp
    permission: betterwarps.cmd

permissions:
  betterwarps.cmd:
    description: Permission to manage warps
    default: op
  betterwarps.warp:
    description: Permission to warp
    default: true
